### ISSUE TITLE
image dimension errors

### ISSUE THREAD

**Issue by t4k** [samvera/serverless-iiif#120]
likely related to my previous issue #116

I'm now using 4.3.3 and found another situation where errors are occurring.

https://bfp3moalhxhpcrwmztmhq6z27e0fkeok.lambda-url.us-west-2.on.aws/iiif/2/collections/Palomar/PP18_v01_1936-1937/output_image_vips/full/full/0/default.jpg does not work: The image “…” cannot be displayed because it contains errors. (Meanwhile, smaller versions work fine: [100px](https://bfp3moalhxhpcrwmztmhq6z27e0fkeok.lambda-url.us-west-2.on.aws/iiif/2/collections/Palomar/PP18_v01_1936-1937/output_image_vips/full/100,/0/default.jpg), [1000px](https://bfp3moalhxhpcrwmztmhq6z27e0fkeok.lambda-url.us-west-2.on.aws/iiif/2/collections/Palomar/PP18_v01_1936-1937/output_image_vips/full/1000,/0/default.jpg))

Relevant CloudWatch entries:

`2023-08-10T17:42:48.472Z	d8596df6-5377-4055-be0a-cc11ee6133bb	WARN	Unable to get dimensions for collections/Palomar/PP18_v01_1936-1937/output_image_vips using custom function. Falling back to sharp.metadata().`

```
2023-08-10T17:42:49.764Z	d8596df6-5377-4055-be0a-cc11ee6133bb	ERROR	TypeError: Cannot read properties of undefined (reading 'toString')
    at /var/task/cache.js:31:54
    at new Promise (<anonymous>)
    at makeCache (/var/task/cache.js:29:10)
    at handleImageRequestFunc (/var/task/index.js:70:13)
    at async handleResourceRequestFunc (/var/task/index.js:49:14)
    at async Runtime.handleRequestFunc [as handler] (/var/task/index.js:24:16)
```

VIPS-encoded pyramid TIFF: https://test-alchemist-betawork.s3.us-west-2.amazonaws.com/collections/Palomar/PP18_v01_1936-1937/output_image_vips.ptif
Original TIFF: https://test-alchemist-betawork.s3.us-west-2.amazonaws.com/collections/Palomar/PP18_v01_1936-1937/source_image.tif

This occurs with an ImageMagick-encoded pyramid TIFF as well.

I first noticed there was an issue when the right column of tiles were not rendering correctly in my viewer: 
![image](https://github.com/samvera/serverless-iiif/assets/415179/b6edddb8-e142-43db-8937-8b096adcb102)

**Comment by mbklein** [comment]
Interesting. If it were having issues getting the dimensions, nothing would work (up to and including the [`info.json` request](https://bfp3moalhxhpcrwmztmhq6z27e0fkeok.lambda-url.us-west-2.on.aws/iiif/2/collections/Palomar/PP18_v01_1936-1937/output_image_vips/info.json). So that doesn't seem to be it. I'm out of the office today, but I'll take a look at this as soon as I can. Thanks for sharing the image files. It'll be a huge help.

**Comment by mbklein** [comment]
@t4k There was a bug in the code that checks the response size. The image that's erroring is 10409107 bytes, which exceeds the 6MB intrinsic Lambda Function URL maximum. Since you're not using the cloudfront-enabled version of the application that includes the workaround for that limit, it's trying to display an error, but the code was trying to get the size from the wrong place.

I've just deployed v4.3.4 with a fix for the issue – you'll get a more useful error message on that request now. You could switch over to the CloudFront version with the workaround, but I'd hold off for the moment. `serverless-iiif` v5.0 is currently in review and will be able to deliver responses >6MB directly from the lambda.

**Comment by gb5256** [comment]
Hi @t4k : 
it looks like you use the Univerisal-Viewer to display files from the servless-iiif.
Would you mind sharing the config you used in calling the viewer? I do not get it to work...
