### ISSUE TITLE
Which viewers work best with serverless-iiif?

### ISSUE THREAD

**Issue by gb5256** [samvera/serverless-iiif#129]
Hi,
I am just starting with IIIF and serverless-IIF.
Tried to have a demo setup to test it.
Stuggeling right now with some of the IIF viewers out there.

But I want to rule out that I am using a IIF viewer which is known to have issues (or specifically issues with the TIF that serverless-IIF is preferring).

So the question is: Which IIF viewers do you successfully use with this?

Thanks for any recommendation.
gb5256

**Comment by t4k** [comment]
Any viewer that can handle a IIIF service should work. They all have different configurations. You'll also have to ensure that your manifests are created well for a viewer to use them.

As you noted in the closed issue #120, we are currently using the Universal Viewer and the only configuration customization is done in a `<script>` element on the page. Feel free to inspect the source and view the manifest files as well: [Caltech Archives Palomar Observatory Records 18-Inch Schmidt Telescope Photographic Plate Logbook 1](https://digital.archives.caltech.edu/collections/Palomar/PP18_v01_1936-1937/)

**Comment by mbklein** [comment]
Hi @gb5256, and thanks for your question. The type of TIFF files that serverless-iiif prefers shouldn't be an issue for any viewer, because by the time the images get to the viewer, they've already been sliced and converted to another format (usually JPEG).

That said, I know some users have been having issues with OpenSeadragon v4.x – rolling back to v3.1.0 seems to do the trick. If that's the viewer you're struggling with, it might not be you (or the server 😄).

If you're not already signed up for the IIIF Slack team, I'd suggest you [request an invitation](https://docs.google.com/forms/d/e/1FAIpQLSdGV9QSFo8i2z1R5iIMP7B2JVhS9akHqcykWF5_y4mtWqVrBA/viewform) and check out the #beginners channel. There's a lot of great information, and it's a great place to ask questions about getting things working with any given viewer.

**Comment by gb5256** [comment]
> Hi @gb5256, and thanks for your question. The type of TIFF files that serverless-iiif prefers shouldn't be an issue for any viewer, because by the time the images get to the viewer, they've already been sliced and converted to another format (usually JPEG).
> 
> That said, I know some users have been having issues with OpenSeadragon v4.x – rolling back to v3.1.0 seems to do the trick. If that's the viewer you're struggling with, it might not be you (or the server 😄).
> 
> If you're not already signed up for the IIIF Slack team, I'd suggest you [request an invitation](https://docs.google.com/forms/d/e/1FAIpQLSdGV9QSFo8i2z1R5iIMP7B2JVhS9akHqcykWF5_y4mtWqVrBA/viewform) and check out the #beginners channel. There's a lot of great information, and it's a great place to ask questions about getting things working with any given viewer.

Hi @mbklein : Thanks for the tip with OpenSeaDragon Version 3.1. That in deed works nicely.
So this now confirms that the AWS is setup correctly and that the file is also tiled correctly. Nice !
I will now start to use more complex manifests and multipage objects, like with Universial Viewer.

Thanks everbody for the help.

gb5256
