### ISSUE TITLE
Error: Input image exceeds pixel limit

### ISSUE THREAD

**Issue by t4k** [samvera/serverless-iiif#135]
[Original title: still seem to hit a 6 MB limit]

I have finally gotten around to trying out the 5.x version. Having followed the development fairly closely, I'm under the impression that the 6 MB limit should not be an issue anymore (see [README commit](https://github.com/samvera/serverless-iiif/commit/35e019ad930eff61370d09138983a5cd8266d03b#diff-1ecb1e1484203254603d82d2feadc0f481ad2758d9511e42fb5230a026bab134)).

I just spun up this stack today and dropped some images in my bucket to try it out and I'm having the issue of `Error: Input image exceeds pixel limit`.

Working 351 KB: [image](https://snkorlqonan6azlbpb6hc26mra0gqvpl.lambda-url.us-west-2.on.aws/iiif/2/351KB/full/max/0/default.webp) [info](https://snkorlqonan6azlbpb6hc26mra0gqvpl.lambda-url.us-west-2.on.aws/iiif/2/351KB/info.json)
Broken 13.4 MB: [image](https://snkorlqonan6azlbpb6hc26mra0gqvpl.lambda-url.us-west-2.on.aws/iiif/2/13MB/full/max/0/default.webp) [info](https://snkorlqonan6azlbpb6hc26mra0gqvpl.lambda-url.us-west-2.on.aws/iiif/2/13MB/info.json)

Am I under the wrong impression? Are there any logs that would be helpful?

Thank you for all the work, btw!

**Comment by mbklein** [comment]
The 6MB limit isn't about your source images; it's about the size of the response. For example, our source bucket contains pyramid TIFFs that are tens of megabytes in size. Our largest is 86MB. If I request it at `/full/full/0/default.jpg`, the response is 69MB, but it works. You'd never run into the 6MB limit requesting an `info.json` because the response will never be more than 1 or 2KB.

The issue I think you're running into is that your full size source image has more total pixels in it than the underlying image processing library, so it's failing to even load it. It's not a limit on the width or the height, but a total WxH limit of 268402689 pixels. The thing that's confusing me about it is that [this constructor option](https://github.com/samvera/node-iiif/blob/main/src/transform.js#L28) is supposed to override that limit. It seems not to be working.

Would you be able to share the broken source image with me so that I can do some troubleshooting with it? And can you confirm that you're using the current version of serverless-iiif? (v5.0.1) That will help me understand exactly which versions of the dependencies are deployed.

That last question has also giving me the idea to create some kind of diagnostic output for the lambda, but without compromising security. I'll have to mull that one over a bit.

**Comment by t4k** [comment]
Very clarifying! Thank you! I didn't understand there was a total pixel limit (even though the error message says exactly that).

I can confirm that I'm using the v5.0.1 stack. I see serverlessrepo:semanticVersion	5.0.1 in the tags.

[1.10-22.ptif.zip](https://github.com/samvera/serverless-iiif/files/13625557/1.10-22.ptif.zip) I had to zip the file because of GitHub limitations. It is a pyramid TIFF and I use the .ptif extension to help me keep track of that. I hadn't actually looked at the dimensions of the image, and this one is ridiculously large for not being a map of some kind (19149 × 19469 pixels).

If it comes down to it I can probably do some processing of our access images so that they conform to a limit, but I'm hoping it can work smoothly without that.

**Comment by mbklein** [comment]
Ahhh, I see it now. I had `limitInputPixels` [here](https://github.com/samvera/node-iiif/blob/main/src/transform.js#L28) but not [here](https://github.com/samvera/node-iiif/blob/941049d7a6d51c3a14a028872d4cde21abfe37ed/src/processor.js#L105). I've fixed it now and pushed `node-iiif` v4.0.3 and `serverless-iiif` v5.0.2, so you should be good to go if you update your stack.

That said, the reason you ran into this in the first place (and I'm glad you did, because it surfaced the bug) is that `serverless-iiif` has to read the image metadata on the fly at runtime. I have just noticed that the docs are missing this next bit of information, but if you add `width` and `height` (and, optionally, `pages`, indicating the number of pre-sized resolutions within your ptiff) [metadata](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata) to your S3 objects, `serverless-iiif` will use that instead and save a lot of runtime overhead.

**Comment by t4k** [comment]
Excellent! I can add metadata. The metadata headers that would be used are formatted like these?

`x-amz-meta-width`, `x-amz-meta-height`, and `x-amz-meta-pages`

**Comment by mbklein** [comment]
If you're using the S3 API directly, yes, those are the headers. If you're using the AWS console, CLI, or any of the official SDKs, you just use the names (`width`, `height`, `pages`) and they'll turn them into the proper headers for you. Unfortunately, it's not possible to _only_ update the metadata on an existing object – you have to copy the object onto itself with the new metadata. But once you make it part of your workflow, it should be pretty smooth.
