### ISSUE TITLE
Dimension function warnings

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [samvera/serverless-iiif#35]
Hello,

I've been testing this out and in the cloudwatch logs and am seeing alot of this kind of thing

`WARN	Unable to get dimensions for [image-id] using custom function. Falling back to probe().`

Is that normal? Or is there something wrong with my source images?

Thanks,

Joseph Anderson

**Comment by mbklein** [comment]
There's nothing _wrong_ with your source images, but they're not “pre-dimensioned.” Retrieving image dimensions is a pretty expensive task at scale, so `serverless-iiif` lets you cheat a little: It does a [HEAD request](https://github.com/samvera-labs/serverless-iiif/blob/main/src/resolvers.js#L18-L31) on the S3 object, and if it finds `width` and `height` metadata properties, it returns those instead of loading the stream and probing the image for size information.

**Comment by mbklein** [comment]
You certainly could do that in a fork, but I don't think that's a feature we're looking for in core – especially since there's no guarantee that the lambda function will have write access to the S3 bucket/objects in question. Depending on your workflow, you could also create an [S3 Lambda trigger function](https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html) that would watch for image objects being added to the S3 bucket and update their metadata in place.
